source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'SwiftyJSON', :git => "git@github.com:SwiftyJSON/SwiftyJSON.git", :branch => 'xcode6.3'
pod 'Alamofire', :git => "git@github.com:Alamofire/Alamofire.git", :branch => 'xcode-6.3'
pod 'PureLayout'
pod 'DateTools'
pod 'SDWebImage', '~>3.6'
pod 'SZTextView'
pod 'Locksmith'

